In [1]:
import numpy as np
from sklearn import svm
import cv2
import matplotlib.pyplot as plt
import os
import math

In [2]:
def plot_images(list_of_images, max_col = 4):
    n = len(list_of_images)
    if n == 1:
        plt.imshow(list_of_images[0]); plt.axis('off'); plt.show()
    else:
        # get number of columns and rows required
        r, c = 1, n
        if n > max_col:
            c = max_col
            r = int(math.ceil(n/max_col))
    
        fig = plt.figure(figsize=(17, max_col * r))
        for i, (img,name) in enumerate(list_of_images):
            ax = fig.add_subplot(r, c, (i+1))
            ax.set_title(str(name))
            ax.axis('off')
            ax.imshow(img)


In [55]:
def get_train(path, label):
    path += "train/" + label + "/"
    
    dataset = np.ndarray(shape=(len(train_files), channels, image_height, image_width),
                     dtype=np.float32)

    i = 0
    for _file in train_files:
        img = load_img(folder + "/" + _file)  # this is a PIL image
        img.thumbnail((image_width, image_height))
        # Convert to Numpy Array
        x = img_to_array(img)  
        x = x.reshape((3, 120, 160))
        # Normalize
        x = (x - 128.0) / 128.0
        dataset[i] = x
        i += 1
        if i % 250 == 0:
            print("%d images to array" % i)
    print("All images to array!")

In [96]:
def get_train(path_dir, category, n_images):
    """
    @description Imports a selected number of resized and flattened images to grayscale
    @param path_dir Root directory for your image dataset
    @param category Category of images to choose from
    @param n_images Number of images you'd like to import
    """
    path_dir += '/train/' + category + '/'
    files_name = os.listdir(path_dir)
    imgs = []
    for c, f in enumerate(files_name):
        if c == n_images:
            break
        img = cv2.imread(path_dir + f, cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (100, 100))
        img_flat = img.flatten()
        imgs.append(img_flat)
    return np.array(imgs)
            
def get_test(path):
    files_name = os.listdir(path + "/test/")
    imgs = []
    for c, f in enumerate(files_name):
        imgs.append(cv2.imread(path + "/test/" + f))
        if c > 10:
            break
            
    return np.array(imgs)

In [97]:
DIRECTORY = 'C:/Users/matth/Downloads/MIO-TCD-Classification'
N_IMAGES = 100

imgs_car = get_train(DIRECTORY, 'car', N_IMAGES)
imgs_bicycle = get_train(DIRECTORY, 'bicycle', N_IMAGES)

x_tr = np.concatenate((imgs_car, imgs_bicycle))
y_tr = np.concatenate(([1 for i in range(N_IMAGES)], [0 for i in range(N_IMAGES)]))

In [98]:
print(x_tr)
# print(x_tr[0:2])
# print((x_tr).shape)
print(x_tr.shape)
print(y_tr.shape)

[[ 46  48  49 ...  80  82  82]
 [ 90 110 123 ... 168 168 168]
 [144 145 146 ... 137 138 140]
 ...
 [182 116  82 ... 151 148 143]
 [  1   1   2 ... 207 206 205]
 [165 165 165 ... 182 177 146]]
(200, 10000)
(200,)


In [99]:
def smv(x_train, y_train, x_val, y_val):
    model = svm.SVC()
    model.fit(x_train, y_train)
    preds = model.predict(x_val, y_val)
    return preds

In [100]:
smv(x_tr, y_tr, x_tr[:10], y_tr[:10])

C:\ProgramData\Anaconda3\envs\opencv-env\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


TypeError: predict() takes 2 positional arguments but 3 were given